core:
  - app/views/layouts/decidim/_head_extra.html.erb
  - app/views/layouts/decidim/_main_footer.html.erb
  - app/views/layouts/decidim/_mini_footer.html.erb
  - app/views/layouts/decidim/_wrapper.html.erb
proposals:
  - app/controllers/decidim/proposals/proposals_controller.rb
