version: '3'
services:
  database:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  app:
    image: decidim-app:latest
    volumes:
      - node_modules:/app/node_modules
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=database
      - DATABASE_USERNAME=postgres
      - DECIDIM_HOST=0.0.0.0
    ports:
      - 3000:3000
    depends_on:
      - database
volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
